<a href="https://colab.research.google.com/github/Mmmm73/K_means-02/blob/main/Clustering_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import pandas as pd

In [58]:
data = pd.read_csv('/content/cluster_analysis_dataset.csv')

In [59]:
data.head()

Feature_1  Feature_2
0   2.248357   1.930868
1   2.323844   2.761515
2   1.882923   1.882932
3   2.789606   2.383717
4   1.765263   2.271280

In [60]:
data.shape #check the shape

(300, 2)

In [61]:
data.isnull().sum()

Feature_1    0
Feature_2    0
dtype: int64

In [64]:
data = pd.DataFrame(data) #create dataframe from data

In [65]:
from sklearn import cluster

In [66]:
k_means=cluster.KMeans(n_clusters=2, max_iter=100, random_state=1) #initialize Kmeans algorithm

In [67]:
k_means

KMeans(max_iter=100, n_clusters=2, random_state=1)

In [68]:
k_means.fit(data) #Train the model


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(max_iter=100, n_clusters=2, random_state=1)

In [69]:
labels=k_means.labels_

In [70]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], d

In [71]:
k_means.cluster_centers_

array([[3.45984959, 1.47693741],
       [8.06412436, 8.02174382]])

In [72]:
labels_df = pd.DataFrame({'labels': labels})

In [73]:
labels_df

labels
0         0
1         0
2         0
3         0
4         0
..      ...
295       0
296       0
297       0
298       0
299       0

[300 rows x 1 columns]

In [74]:
merge = pd.concat([data,labels_df], axis=1)

In [75]:
merge

Feature_1  Feature_2  labels
0     2.248357   1.930868       0
1     2.323844   2.761515       0
2     1.882923   1.882932       0
3     2.789606   2.383717       0
4     1.765263   2.271280       0
..         ...        ...     ...
295   5.035783   0.761171       0
296   5.239490   1.166831       0
297   5.518770   0.744992       0
298   4.865063   0.510618       0
299   4.777853   1.188650       0

[300 rows x 3 columns]

In [77]:
merge['Feature_1'].max() #max value of feature 1

9.157329283336754

In [78]:
merge['Feature_1'].min() #min value of feature 1

0.6901274479551278

In [79]:
merge['Feature_2'].max() #max value of feature 2

9.92636574532736

In [80]:
merge['Feature_2'].min() #min value of feature 2

-0.1509605823677924

In [81]:
import numpy as np

In [82]:
feature_1_values = np.random.uniform(merge['Feature_1'].min(), merge['Feature_1'].max(), 5) #5 random values for feature 1 within the range of min and max

In [83]:
feature_1_values

array([7.57004909, 7.11304134, 6.8839456 , 0.99750625, 0.93408146])

In [84]:
feature_2_values = np.random.uniform(merge['Feature_2'].min(), merge['Feature_2'].max(), 5) #5 random values for feature 2 within the range of min and max

In [85]:
feature_2_values

array([9.09555648, 4.91802098, 1.40422997, 8.50262079, 1.02220026])

In [86]:
merged_array = np.column_stack((feature_1_values, feature_2_values)) #merge the arrays

In [87]:
merged_array

array([[7.57004909, 9.09555648],
       [7.11304134, 4.91802098],
       [6.8839456 , 1.40422997],
       [0.99750625, 8.50262079],
       [0.93408146, 1.02220026]])

In [88]:
type(merged_array)

numpy.ndarray

In [89]:
labels_test=k_means.predict(merged_array)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


In [90]:
labels_test

array([1, 1, 0, 1, 0], dtype=int32)

In [91]:
labels_test=labels_test.reshape(-1,1) #Reshape array into 2-D array

In [92]:
labels_test

array([[1],
       [1],
       [0],
       [1],
       [0]], dtype=int32)

In [93]:
cols=data.columns.tolist()

In [94]:
cols

['Feature_1', 'Feature_2']

In [95]:
merged_array

array([[7.57004909, 9.09555648],
       [7.11304134, 4.91802098],
       [6.8839456 , 1.40422997],
       [0.99750625, 8.50262079],
       [0.93408146, 1.02220026]])

In [96]:
labels_test

array([[1],
       [1],
       [0],
       [1],
       [0]], dtype=int32)

In [97]:
cols

['Feature_1', 'Feature_2']

In [98]:
cols.append('Cluster ID') #Add column 'Cluster ID' to original column list

In [99]:
newData = pd.DataFrame(np.concatenate((merged_array,labels_test), axis=1), columns=cols)

In [100]:
newData

Feature_1  Feature_2  Cluster ID
0   7.570049   9.095556         1.0
1   7.113041   4.918021         1.0
2   6.883946   1.404230         0.0
3   0.997506   8.502621         1.0
4   0.934081   1.022200         0.0