<a href="https://colab.research.google.com/github/Mmmm73/K_means-02/blob/main/Clustering_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [5]:
data = pd.read_csv('/content/cluster_analysis_dataset.csv')

In [6]:
data.head()

Feature_1  Feature_2
0   2.248357   1.930868
1   2.323844   2.761515
2   1.882923   1.882932
3   2.789606   2.383717
4   1.765263   2.271280

In [8]:
data.shape #check the shape

(300, 2)

In [9]:
data.isnull().sum()

Feature_1    0
Feature_2    0
dtype: int64

In [11]:
from sklearn import cluster

In [12]:
k_means=cluster.KMeans(n_clusters=2, max_iter=100, random_state=1) #initialize Kmeans algorithm

In [13]:
k_means

KMeans(max_iter=100, n_clusters=2, random_state=1)

In [14]:
k_means.fit(data) #Train the model


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(max_iter=100, n_clusters=2, random_state=1)

In [15]:
labels=k_means.labels_

In [16]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], d

In [17]:
k_means.cluster_centers_

array([[3.45984959, 1.47693741],
       [8.06412436, 8.02174382]])

In [20]:
data_df = pd.DataFrame(data) #create dataframe from data

In [21]:
data_df

Feature_1  Feature_2
0     2.248357   1.930868
1     2.323844   2.761515
2     1.882923   1.882932
3     2.789606   2.383717
4     1.765263   2.271280
..         ...        ...
295   5.035783   0.761171
296   5.239490   1.166831
297   5.518770   0.744992
298   4.865063   0.510618
299   4.777853   1.188650

[300 rows x 2 columns]

In [22]:
labels_df = pd.DataFrame({'labels': labels})

In [23]:
labels_df

labels
0         0
1         0
2         0
3         0
4         0
..      ...
295       0
296       0
297       0
298       0
299       0

[300 rows x 1 columns]

In [24]:
merge = pd.concat([data_df,labels_df], axis=1)

In [25]:
merge

Feature_1  Feature_2  labels
0     2.248357   1.930868       0
1     2.323844   2.761515       0
2     1.882923   1.882932       0
3     2.789606   2.383717       0
4     1.765263   2.271280       0
..         ...        ...     ...
295   5.035783   0.761171       0
296   5.239490   1.166831       0
297   5.518770   0.744992       0
298   4.865063   0.510618       0
299   4.777853   1.188650       0

[300 rows x 3 columns]

In [ ]:
outcome=pd.DataFrame(labels, index=movies.User, columns=['Cluster ID'])

In [27]:
merge['Feature_1'].max() #max value of feature 1

9.157329283336754

In [28]:
merge['Feature_1'].min() #min value of feature 1

0.6901274479551278

In [29]:
merge['Feature_2'].max() #max value of feature 2

9.92636574532736

In [30]:
merge['Feature_2'].min() #min value of feature 2

-0.1509605823677924

In [31]:
import numpy as np

In [33]:
feature_1_values = np.random.uniform(merge['Feature_1'].min(), merge['Feature_1'].max(), 5) #5 random values for feature 1 within the range of min and max

In [34]:
feature_1_values

array([7.62061498, 1.57837908, 2.07959128, 2.4628125 , 9.11486488])

In [35]:
feature_2_values = np.random.uniform(merge['Feature_2'].min(), merge['Feature_2'].max(), 5) #5 random values for feature 2 within the range of min and max

In [36]:
feature_2_values

array([8.43237607, 7.85807761, 5.43471467, 3.41429235, 9.46780628])

In [41]:
merged_array = np.column_stack((feature_1_values, feature_2_values)) #merge the arrays

In [42]:
merged_array

array([[7.62061498, 8.43237607],
       [1.57837908, 7.85807761],
       [2.07959128, 5.43471467],
       [2.4628125 , 3.41429235],
       [9.11486488, 9.46780628]])

In [43]:
type(merged_array)

numpy.ndarray

In [44]:
labels_test=k_means.predict(merged_array)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


In [45]:
labels_test

array([1, 1, 0, 0, 1], dtype=int32)

In [46]:
labels_test=labels_test.reshape(-1,1) #Reshape array into 2-D array

In [47]:
labels_test

array([[1],
       [1],
       [0],
       [0],
       [1]], dtype=int32)

In [48]:
cols=data.columns.tolist()

In [49]:
cols

['Feature_1', 'Feature_2']

In [51]:
merged_array

array([[7.62061498, 8.43237607],
       [1.57837908, 7.85807761],
       [2.07959128, 5.43471467],
       [2.4628125 , 3.41429235],
       [9.11486488, 9.46780628]])

In [52]:
labels_test

array([[1],
       [1],
       [0],
       [0],
       [1]], dtype=int32)

In [53]:
cols

['Feature_1', 'Feature_2']

In [54]:
cols.append('Cluster ID') #Add column 'Cluster ID' to original column list

In [55]:
newData = pd.DataFrame(np.concatenate((merged_array,labels_test), axis=1), columns=cols)

In [56]:
newData

Feature_1  Feature_2  Cluster ID
0   7.620615   8.432376         1.0
1   1.578379   7.858078         1.0
2   2.079591   5.434715         0.0
3   2.462812   3.414292         0.0
4   9.114865   9.467806         1.0